golagola2020/hango-mobile

arduino/three_ultraJson_accuracy/three_ultraJson_accuracy.ino
arduino/three_ultraJson_accuracy/three_ultraJson_accuracy_function.ino

초음파 센서 수량 변경, 자판기 음료수 10개로 변경
자판기 모형이 변경되며 음료 판매종류가 10 종류로 바뀌어 손을 측정하는 초음파 센서는 2개만 사용하게 되어 코드를 바꾸었습니다.
Signed-off-by: Ahnhyesu <linim@naver.com>

[arduino/ultra] 초음파 센서 수량 변경, 자판기 음료수 10개로 변경

---

mobile/login/app/src/main/AndroidManifest.xml
mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/res/drawable/btn_radius.xml
mobile/login/app/src/main/res/layout/activity_info.xml
mobile/login/app/src/main/res/layout/activity_main.xml

회원 탈퇴 기능 구현 완료
1. 유저 정보 화면 디자인
2. 메인화면에서 유저 정보화면으로 이동
3. 회원 탈퇴 기능

[mobile/userInfo] 회원 탈퇴 기능 구현 완료

---

mobile/login/app/src/main/java/com/example/loginactivity/DrinkItem.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/res/layout/add_drink_item.xml

[mobile/drinkpage]음료정보 화면 기능구현(음료 추가 버튼 기능)
서버로 부터 음료정보를 파싱해와서 GridView에 음료정보 출력후 마지막 View에 음료 추가버튼이 추가되도록 함

[mobile/dirnkpage]음료정보 화면 기능구현(음료 추가 버튼 기능)

---

mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java

[mobile/logout] 로그아웃 구현 완료

---

mobile/login/app/src/main/java/com/example/loginactivity/LoginRequest.java
mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingRequest.java

[mobile/userInfoDebug] 서버 통신 테스트를 위한 url 변경

[mobile/userInfoDebug] 서버 통신 테스트를 위한 url 변경

---

mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java

[mobile/userInfoDebug] 리펙토링 완료
[mobile/userInfoDebug] 리펙토링 완료

[mobile/userInfoDebug] 리펙토링 완료

---

mobile/login/app/src/main/java/com/example/loginactivity/SignupActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
mobile/login/app/src/main/res/layout/activity_signup.xml

[mobile/editSignup] 회원가입시 이메일 입력 및 저장 기능 구현

[mobile/editSignup] 회원가입시 이메일 입력 및 저장 기능 구현

---

mobile/login/app/src/main/AndroidManifest.xml
mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/InfoUpdateActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/LoginActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/SignupActivity.java
mobile/login/app/src/main/res/layout/activity_info_update.xml
mobile/login/app/src/main/res/layout/activity_login.xml
mobile/login/app/src/main/res/layout/activity_signup.xml

[mobile/updateInfo] 회원 정보 변경 화면 구현

---

mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/VendingData.java
mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java

메인화면 ListView 기능별 객체화 및 버그 수정
목적 : 기능별 객체화를 통해 버그를 수정하기 위함
1. 자판기 정보가 저장되는 VendingData 클래스에서 각 자판기 변수들을
getter와 setter로 접근하도록 하였습니다
2. ListView Adapter를 객체화 하였습니다
3. 각 ListView item 클릭시 화면이 전환되도록 수정하였습니다
4. 각 버튼 클릭시 앱이 강제종료 되던 오류를 수정 하였습니다

[mobile/mainpage]메인화면 ListView 기능별 객체화 및 버그 수정

---

arduino/four_ultrasonic/four_ultrasonic.ino
arduino/four_ultrasonic/four_ultrasonic_py.py

[rasp/transJson] 초음파 센서값을 가공해 Json으로 변환 +serialNumber
시리얼 넘버를 추가했다.

[rasp/transJson] 초음파 센서값을 가공해 Json으로 변환 +serialNumber

---

mobile/login/app/src/main/java/com/example/loginactivity/InfoUpdateActivity.java

[Server/fix updated info json] 회원 정보 수정의 JSON 교환 형식 변경 완료

[Server/fix updated info json] 회원 정보 수정의 JSON 교환 형식 변경 완료

---

mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/res/layout/activity_main.xml
mobile/login/app/src/main/res/layout/listview_item.xml

[mobile/mainpage]ListView item 클릭 이벤트 오류 수정
ListView item 클릭이 안되는 오류를 수정

[mobile/mainpage]ListView item 클릭 이벤트 오류 수정

---

arduino/four_ultrasonic/four_ultrasonic.ino
arduino/four_ultrasonic/four_ultrasonic_py.py

Json 출력방식 변경 
우림씨가 요청한대로 {"serialNumber": 20200814042555141, "sensing": {"duplicate": "zero", "drink": "non", "hand": "non"}}로 변경

[rasp/transJson] Json 출력방식 변경 

---

arduino/four_ultrasonic/four_ultrasonic.ino
arduino/four_ultrasonic/four_ultrasonic_py.py

하드웨어 코드 리펙토링
1. 아두이노 코드
2. 라즈베리파이 코드

[Hardware/refectoring] 하드웨어 코드 리펙토링

---

arduino/four_ultrasonic/four_ultrasonic_py.py

[hardware/refectoring] 라즈베리파이 오타 수정

[hardware/refectoring] 라즈베리파이 오타 수정

---

arduino/four_ultrasonic/four_ultrasonic.ino
arduino/four_ultrasonic/four_ultrasonic_py.py
mobile/login/app/src/main/AndroidManifest.xml
mobile/login/app/src/main/java/com/example/loginactivity/AddDrinkActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/res/layout/activity_add_drink.xml
mobile/login/app/src/main/res/layout/add_drink_item.xml

[rasp/request drinks]서버에게 음료수 데이터 보내기
서버에게 음료수 데이터 보내기

[rasp/request drinks]서버에게 음료수 데이터 보내기

---

arduino/rasp.py

1. 코드 단축
2. is_available() 함수 추가
3. 아두이노에서 전송하는 데이터가 올바른지 판단한 후에 서버에 전송하도록 하였음

[hardware/refectoring] 라즈베리파이 기능 개선

---

mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java

[Mobile/drinkpage]음료 수정 팝업창 구현
음료 수정 팝업창 구현

[Mobile/drinkpage]음료 수정 팝업창 구현

---

arduino/rasp.py

[rasp/requestDrinksUpdate] 판매된 음료 정보 차감 함수 구현

[rasp/requestDrinksUpdate] 판매된 음료 정보 차감 함수 구현

---

arduino/rasp.py

[hardware/refectoring] 음료 정보 요청 기능 개선
Signed-off-by: parkwoorim<woorimprog@gmail.com>

[hardware/refectoring] 음료 정보 요청 기능 개선

---

arduino/rasp.py

[rasp/speakReceivedDrinks] speak() 함수 구현 완료

[rasp/speakReceivedDrinks] speak() 함수 구현 완료

---

mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/InfoActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/InfoUpdateActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/SignupRequest.java
mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java
mobile/login/app/src/main/res/layout/activity_main.xml

[Mobile/mainpage]자판기 검색기능 구현 및 버그 수정
1.자판기 검색기능을 구현함
2. 자판기 리스트뷰 중복 출력 버그 수정
3. 자판기 리스트뷰 스크롤 시 데이터 섞임 오류 수정

[Mobile/mainpage]자판기 검색기능 구현 및 버그 수정

---

mobile/login/app/src/main/java/com/example/loginactivity/DrinkItem.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/res/layout/activity_main.xml
mobile/login/app/src/main/res/layout/drink_item.xml

[Mobile/drinkpage]음료정보 GridView 오류 수정
음료정보 GridView 오류를 수정함

[Mobile/drinkpage]음료정보 GridView 오류 수정

---

arduino/rasp.py

[rasp/speakRecievedDrinks]서버에게 전달받은 음료 데이터를 스피커로 출력.
서버에서 전달받은 음료 데이터를 스피커로 상황마다 출력할 수 있다.

[rasp/speakRecievedDrinks]서버에게 전달받은 음료 데이터를 스피커로 출력.

---

arduino/real_auto_hango/real_auto_hango.ino
arduino/아두이노 주석

아두이노 코드 리펙토링
1.주석처리 변경 완료.
2.음료 버튼 양옆 공간, 버튼사이의 거리 두 가지를 상수로 설정 완료
Signed-off-by: HyesuAhn <linim@naver.com>

[hardware/refectoring] 아두이노 코드 리펙토링

---

arduino/real_auto_hango/real_auto_hango.ino

아두이노 코드 리펙토링, break추가 완료
break추가 완료 및 줄맞춤 완료.
Signed-off-by: HyesuAhn <linim@naver.com>

[hardware/refectoring]아두이노 코드 리펙토링, break추가 완료

---

arduino/asyncTest.py

[rasp/multiProcess] 멀티 프로세싱 테스트 구문 구현 완료
Signed-off-by: 박우림 <woorimprog@gmail.com>

[rasp/multiProcess] 멀티 프로세싱 테스트 구문 구현 완료

---

arduino/asyncTest.py
arduino/rasp.py

[rasp/multiProcessing] 멀티프로세싱 라즈베리파이 적용 완료

[rasp/multiProcessing] 멀티프로세싱 라즈베리파이 적용 완료

---

hardware/raspberry.py

[rasp/speakSoldout] 품절 정보 출력 기능 구현 완료

[rasp/speakSoldout] 품절 정보 출력 기능 구현 완료

---

hardware/raspberry.py

[rasp/speakSoldout] 오타 수정

---

mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java

자판기 수정 실시간 갱신 기능 구현
자판기 수정 실시간 갱신 기능 구현

[mobile/mainpage]자판기 수정 실시간 갱신 기능 구현

---

hardware/raspberry.py

[Hotfix] 라즈베리파이 품절 정보 출력 오류 해결

[Hotfix] 라즈베리파이 품절 정보 출력 오류 해결

---

mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/res/layout/activity_drink_main.xml

음료 refresh 버튼 추가
음료 refresh 버튼 추가

[mobile/drinkpage]음료 refresh 버튼 추가

---

mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/UpdateVendingActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/VendingListAdapter.java

자판기 ListView code refactoring
자판기 ListView code refactoring

[mobile/mainpage]자판기 ListView code refactoring

---

mobile/login/app/src/main/AndroidManifest.xml
mobile/login/app/src/main/java/com/example/loginactivity/AddDrinkActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkRefreshAcceptActivity.java
mobile/login/app/src/main/res/layout/activity_drink_refresh_accept.xml

음료정보 화면 기능 추가 및 수정
1. 음료정보 GridView code refactoring
2. 음료개수 refresh 버튼 기능 구현

[Mobile/drinkpage]음료정보 화면 기능 추가 및 수정

---

README.md

READEME 1차 작업
아두이노및 라즈베리파이에 필요한 설치 정보 생성
Signed-off-by: HyesuAhn <linim@naver.com>

[client/docs]READEME 1차 작업

---

mobile/login/app/src/main/AndroidManifest.xml
mobile/login/app/src/main/java/com/example/loginactivity/DrinkListAdapter.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkMainActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/DrinkRefreshAcceptActivity.java
mobile/login/app/src/main/java/com/example/loginactivity/UpdateDrinkActivity.java
mobile/login/app/src/main/res/drawable/btn_accept.xml
mobile/login/app/src/main/res/drawable/btn_deny.xml
mobile/login/app/src/main/res/drawable/btn_radius.xml
mobile/login/app/src/main/res/drawable/ic_arrow_back.xml
mobile/login/app/src/main/res/drawable/ic_drink_add.xml
mobile/login/app/src/main/res/drawable/ic_info.xml
mobile/login/app/src/main/res/drawable/ic_refresh.xml
mobile/login/app/src/main/res/layout/activity_add_drink.xml
mobile/login/app/src/main/res/layout/activity_drink_main.xml
mobile/login/app/src/main/res/layout/activity_drink_refresh_accept.xml
mobile/login/app/src/main/res/layout/activity_update_drink.xml
mobile/login/app/src/main/res/layout/add_drink_item.xml

음료정보 페이지 UI 수정 및 code refactoring
음료정보 페이지 UI 수정 및 code refactoring

[Mobile/drinkpage]음료정보 페이지 UI 수정 및 code refactoring

---

mobile/login/app/src/main/java/com/example/loginactivity/MainActivity.java
mobile/login/app/src/main/res/drawable/ic_delete.xml
mobile/login/app/src/main/res/drawable/ic_edit.xml
mobile/login/app/src/main/res/drawable/ic_menu.xml
mobile/login/app/src/main/res/drawable/main_shadow.xml
mobile/login/app/src/main/res/layout/activity_main.xml
mobile/login/app/src/main/res/layout/activity_update_vending.xml

[Mobile/mainpage]메인 화면 UI 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java

[mobile/drinkpage]뒤로가기 기능 구현

---

mobile/hango/app/src/main/res/drawable/main_shadow.xml

1. 모서리 corners 효과를 추가하였습니다.
자판기 ListView UI 수정
자판기 ListView UI 수정

[mobile/mainpage]자판기 ListView UI 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/AddDrinkActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
mobile/hango/app/src/main/res/layout/activity_guide_drink_main.xml

음료정보 가이드 화면 수정 및 기능 구현
1. 음료정보 가이드 화면에서 마지막 부분을 '부족' 으로 수정
2. 음료 추가 화면에서 뒤로가기 버튼 기능 구현

[mobile/drinkpage]음료정보 가이드 화면 수정 및 기능 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginActivity.java
mobile/hango/app/src/main/res/layout/activity_login.xml

로그인 정보 저장 기능 구현
1. 로그인 정보 저장기능 구현
2. 로그아웃시 저장된 로그인 정보 삭제 기능 구현

[mobile/login]로그인 정보 저장 기능 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/res/layout/activity_main.xml

자판기 ListView Pull to Refresh 기능 구현
자판기 ListView Pull to Refresh 기능 구현

[mobile/mainpage]자판기 ListView Pull to Refresh 기능 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
mobile/hango/app/src/main/res/layout/activity_drink_main.xml
mobile/hango/app/src/main/res/layout/activity_main.xml

음료정보 GridView Pull to Refresh 기능 구현
음료정보 GridView Pull to Refresh 기능 구현

[mobile/drinkpage]음료정보 GridView Pull to Refresh 기능 구현

---

mobile/hango/app/build.gradle
mobile/hango/app/src/main/java/com/hango/hangoactivity/AddDrinkActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkListAdapter.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/SalesDataMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/UpdateDrinkActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingListAdapter.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingSalesDataActivity.java
mobile/hango/app/src/main/res/layout/activity_drink_main.xml
mobile/hango/app/src/main/res/layout/activity_main.xml
mobile/hango/app/src/main/res/layout/drink_item.xml
mobile/hango/app/src/main/res/layout/listview_item.xml

네이밍 규칙에 따른 변수명 변경 및 라이브러리 제거
사용하지 않는 라이브러리 제거
음료관리 현황 페이지의 네이밍 규칙에 따른 변수명 변경
메인화면의 네이밍 규칙에 따른 변수명 변경

[Mobile/refactoring]네이밍 규칙에 따른 변수명 변경 및 라이브러리 제거

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/AddDrinkActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkRefreshAcceptActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkSalesDataActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/SalesDataMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingSalesDataActivity.java
mobile/hango/app/src/main/res/layout/activity_add_drink.xml

변수명 네이밍 규칙에 따른 변수명 변경
변수명 네이밍 규칙에 따른 변수명 변경

[Mobile/refactoring]변수명 네이밍 규칙에 따른 변수명 변경

---

mobile/hango/app/src/main/res/layout/activity_info.xml

[mobile/info]info 화면 UI 변경

---

mobile/hango/app/src/main/res/layout/activity_signup.xml

잘못된 버튼 text 변경 "로그인" -> "회원가입"
회원가입 화면 회원가입 버튼 text변경
잘못된 버튼 text 변경 "로그인" -> "회원가입"

[mobile/signup]회원가입 화면 회원가입 버튼 text변경

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginActivity.java

로그인시에 서버로 보내는 데이터 형태 변경
로그인시에 서버로 보내는 데이터 형태 변경

[mobile/login]로그인시에 서버로 보내는 데이터 형태 변경

---

mobile/hango/app/src/main/res/layout/activity_main.xml

[mobile/mainpage]매출 통계 버튼 UI 변경

---

mobile/hango/app/src/main/AndroidManifest.xml
mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationThread.java
mobile/hango/app/src/main/res/layout/activity_notification.xml

품절정보 알림 UI 설계 및 기능 구현
품절정보 알림 UI 설계 및 기능 구현

[mobile/info]품절정보 알림 UI 설계 및 기능 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingData.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingListAdapter.java
mobile/hango/app/src/main/res/layout/empty_vending.xml

Signed-off-by: SongKiSu <8345783@naver.com>
userId에 해당하는 자판기 정보가 없을때 ListViewApater의경우 만들기
userId에 해당하는 자판기 정보가 없을때 ListViewApater의경우 만들기

[mobile/mainpage]userId에 해당하는 자판기 정보가 없을때 ListViewApater의경우 만들기

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainBackPressCloseHandler.java

하단 뒤로가기 버튼 기능 막기
하단 뒤로가기 버튼 기능 막기

[mobile/mainpage]하단 뒤로가기 버튼 기능 막기

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoUpdateActivity.java

회원정보 변경시 서버로 보내는 데이터 형태 변경
회원정보 변경시 서버로 보내는 데이터 형태 변경

[mobile/info]회원정보 변경시 서버로 보내는 데이터 형태 변경

---

mobile/hango/app/src/main/AndroidManifest.xml

[mobile/server]http 통신설정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoUpdateActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/res/layout/activity_info_update.xml

[Mobile/info]info화면 UI 수정

---

LICENSE

Apache 2.0 License 생성
Create Apache 2.0 License
Create Apache 2.0 License

Create Apache 2.0 License

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/UpdateDrinkActivity.java

음료정보 update 버그 수정
음료정보 update 버그 수정

[mobile/drinkpage]음료정보 update 버그 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingListAdapter.java
mobile/hango/app/src/main/res/layout/activity_main.xml

[mobile/mainpage]자판기 검색 버그 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoUpdateActivity.java
mobile/hango/app/src/main/res/drawable/textbox_radius_white.xml
mobile/hango/app/src/main/res/layout/activity_info_update.xml

info update UI 수정
info update UI 수정

[mobile/info]info update UI 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java

안드로이드 8.0(sdk26)이상에서의 notification 기능 구현
안드로이드 8.0(sdk26)이상에서의 notification 기능 구현

[mobile/notification]안드로이드 8.0(sdk26)이상에서의 notification 기능 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/SalesDataMainActivity.java
mobile/hango/app/src/main/res/layout/activity_salesdata_main.xml

자판기가 없을때 매출 통계화면 진입시 앱 종료 버그 수정
자판기가 없을때 매출 통계화면 진입시 앱 종료 버그 수정

[mobile/salsedata]자판기가 없을때 매출 통계화면 진입시 앱 종료 버그 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java

자판기가 없을때 자판기 검색시 앱이 종료되는 오류 수정
자판기가 없을때 자판기 검색시 앱이 종료되는 오류 수정

[mobile/mainpage]자판기가 없을때 자판기 검색시 앱이 종료되는 오류 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginBackPressCloseHandler.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java

하단 뒤로가기 버튼 기능 막기
하단 뒤로가기 버튼 기능 막기

[mobile/login]하단 뒤로가기 버튼 기능 막기

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java

안드로이드 8.0(sdk26)이상에서의 background service 구현
안드로이드 8.0(sdk26)이상에서의 background service 구현

[mobile/notification]안드로이드 8.0(sdk26)이상에서의 background service 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkListAdapter.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/DrinkRefreshAcceptActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingListAdapter.java
mobile/hango/app/src/main/res/layout/activity_main.xml

음료추가시 해당 자판기에 해당하는 soldOut SharedPrefences 제거
음료추가시 해당 자판기에 해당하는 soldOut SharedPrefences 제거

[mobile/drinkrefresh]음료추가시 해당 자판기에 해당하는 soldOut SharedPrefences 제거

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java

메인페이지에 license 고지
메인페이지에 license 고지

[mobile/license]메인페이지에 license 고지

---

mobile/hango/app/src/main/AndroidManifest.xml
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingDeleteActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/VendingListAdapter.java
mobile/hango/app/src/main/res/layout/activity_vending_delete.xml

자판기 삭제시 앱이 종료되는 오류 수정
자판기 삭제시 앱이 종료되는 오류 수정

[mobile/mainpage]자판기 삭제시 앱이 종료되는 오류 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/GuideDrinkMainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java

notification 클릭시 메인화면 자판기 목록 출력불가
notification 클릭시 메인화면 자판기 목록 출력불가

[mobile/notification]notification 클릭시 메인화면 자판기 목록 출력불가

---

mobile/hango/app/src/main/AndroidManifest.xml
mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java

안드로이드10.0(sdk29)이상에서의 백그라운드 서비스권한 부여
안드로이드10.0(sdk29)이상에서의 백그라운드 서비스권한 부여

[mobile/notification]안드로이드10.0(sdk29)이상에서의 백그라운드 서비스권한 부여

---

mobile/hango/app/src/main/AndroidManifest.xml
mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/LicenseActivity.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/LicenseListAdapter.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/PrintLicenseActivity.java
mobile/hango/app/src/main/res/layout/activity_info.xml
mobile/hango/app/src/main/res/layout/activity_license.xml
mobile/hango/app/src/main/res/layout/activity_print_license.xml
mobile/hango/app/src/main/res/layout/license_item.xml
mobile/hango/app/src/main/res/raw/android_sdk_license.txt
mobile/hango/app/src/main/res/raw/eaze_graph_license.txt
mobile/hango/app/src/main/res/raw/nine_old_androids_license.txt
mobile/hango/app/src/main/res/raw/volley_license.txt

라이선스 페이지 기능구현 완료
라이선스 페이지 기능구현 완료

[Mobile/licensepage] 라이선스 페이지 기능구현 완료

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/LoginBackPressCloseHandler.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/MainBackPressCloseHandler.java

시스템 백버튼으로 종료시 백그라운드가 종료되는 오류
시스템 백버튼으로 종료시 백그라운드가 종료되는 오류 수정

[mobile/backpressbutton]시스템 백버튼으로 종료시 백그라운드가 종료되는 오류 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/UpdateVendingActivity.java

형식에 맞는 자판기 정보를 받도록 수정
형식에 맞는 자판기 정보를 받도록 수정

[mobile/vendingupdate]형식에 맞는 자판기 정보를 받도록 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/InfoUpdateActivity.java

형식에 맞는 회원 정보를 받도록 수정
형식에 맞는 회원 정보를 받도록 수정

[mobile/info]형식에 맞는 회원 정보를 받도록 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/UpdateDrinkActivity.java

형식에 맞는 음료 정보를 받도록 수정
형식에 맞는 음료 정보를 받도록 수정

[mobile/drinkupdate]형식에 맞는 음료 정보를 받도록 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/AddDrinkActivity.java
mobile/hango/app/src/main/res/layout/activity_info.xml

형식에 맞는 음료정보를 받도록 수정
형식에 맞는 음료정보를 받도록 수정

[mobile/addDrink]형식에 맞는 음료정보를 받도록 수정

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/UpdateVendingActivity.java

[mobile/vendingupdate]뒤로가기 버튼 기능 구현

---

mobile/hango/app/src/main/java/com/hango/hangoactivity/NotificationService.java
mobile/hango/app/src/main/java/com/hango/hangoactivity/UpdateVendingActivity.java

Hango Mobile v2.0 개발 완료
Hango Mobile v2.0 개발 완료

[mobile/v2.0] Hango Mobile v2.0 개발 완료
